services:
  mongodb:
    image: mongo:6.0
    container_name: tech-catalog-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: